# Generated by Django 3.1.1 on 2020-10-02 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='history',
        ),
        migrations.AddField(
            model_name='history',
            name='deal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.deal'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
