# Generated by Django 3.1.1 on 2020-10-05 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201006_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_deal',
            name='host_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_host', to='app.parent_item'),
        ),
        migrations.AlterField(
            model_name='request_deal',
            name='join_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_join', to='app.parent_item'),
        ),
    ]
