# Generated by Django 3.1.1 on 2020-10-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201006_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='denied_reason',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
