# Generated by Django 3.1.1 on 2020-10-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_request_denied_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='give_item',
            name='done_deal',
            field=models.BooleanField(default=False),
        ),
    ]
