# Generated by Django 3.1.1 on 2020-09-14 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200914_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AlterField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app.give_item'),
        ),
        migrations.AlterField(
            model_name='item_image',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_image', to='app.give_item'),
        ),
        migrations.RemoveField(
            model_name='parent_item',
            name='keyword',
        ),
        migrations.AddField(
            model_name='parent_item',
            name='keyword',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_item', to='app.keyword'),
        ),
    ]
