# Generated by Django 3.1.1 on 2020-09-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200915_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent_item',
            name='keyword',
        ),
        migrations.AddField(
            model_name='parent_item',
            name='keyword',
            field=models.ManyToManyField(related_name='parent_item', to='app.Keyword'),
        ),
    ]
