# Generated by Django 3.1.1 on 2020-09-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200916_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bland',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='meeting_time',
            name='request',
        ),
        migrations.AddField(
            model_name='meeting_time',
            name='request',
            field=models.ManyToManyField(related_name='meeting_time', to='app.Request'),
        ),
        migrations.AlterField(
            model_name='meeting_time',
            name='what_time',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='pickup_places',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
