# Generated by Django 3.1.1 on 2020-09-18 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200918_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='give_item',
            name='parent_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='give_item', to='app.parent_item'),
        ),
        migrations.AlterField(
            model_name='want_item',
            name='parent_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='want_item', to='app.parent_item'),
        ),
    ]
