# Generated by Django 3.1.1 on 2020-09-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200919_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.ImageField(blank=True, default='./default_image/ユーザーデフォルト背景画像.jpg', null=True, upload_to='images/'),
        ),
    ]
