# Generated by Django 3.1.1 on 2020-09-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200923_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.ImageField(blank=True, default='images/ユーザーデフォルト背景画像.jpg', null=True, upload_to='images/'),
        ),
    ]
