# Generated by Django 3.1.1 on 2020-09-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200923_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='join_user_accept',
            field=models.BooleanField(default=False),
        ),
    ]
