# Generated by Django 3.1.1 on 2020-09-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_deal_join_user_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
