# Generated by Django 3.1.1 on 2020-09-28 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200925_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickup_places',
            old_name='choosingUser',
            new_name='choosing_user',
        ),
    ]
